#! /bin/sh

xsetroot -cursor_name left_ptr

~/.config/cron-jobs/feh-dynamic-wallpaper.sh &

polybar &

picom --config ~/.config/picom/picom.conf &

killall dunst && dunst &

polybar &

## set up track pad
TRACKPAD_ID=$(xinput list | grep Touchpad | cut -d'=' -f2- | cut -b 1-2)
TAP_ENABLED=$(xinput list-props $TRACKPAD_ID | grep "Tapping Enabled (" | cut -d'(' -f2- | rev | cut -d ')' -f2- | rev)
echo $TAP_ENABLED | xargs -I {} xinput set-prop $TRACKPAD_ID {} 1

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           10
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
